### ISSUE TITLE
Is the masking of rightmost lists necessary?

### ISSUE THREAD

**Issue by ca-d** [OpenEnergyTools/scl-template#1]
I'm somewhat surprised that when I click the right arrow on an LNodeType's DO in order to open the DOType, the DAType and EnumType columns get covered by an empty pane (two rightmost columns in the screenshot below):

![screenshot](https://github.com/OpenEnergyTools/scl-template/assets/20446628/61da6c78-e125-4e26-9b52-4c57585b3bc2)

**Comment by JakobVogelsang** [comment]
I changed that @ca-d . It is more intuitive this way. Thank you for the feedback
